### ISSUE TITLE
Vertical Layout

### ISSUE THREAD

**Issue by walterra** [walterra/d3-milestones#1]
Offer an option to arrange the timeline vertically.

**Comment by sophiec20** [comment]
+1 
vertical layout would be awesome

**Comment by walterra** [comment]
The release `v1.0.0-beta1` adds support for vertical timelines! https://github.com/walterra/d3-milestones/releases/tag/v1.0.0-beta1

![image](https://user-images.githubusercontent.com/230104/83239681-967b8600-a198-11ea-9cf6-c848062b9b99.png)
