### ISSUE TITLE
Top-bottom distribution & label optimization is broken?

### ISSUE THREAD

**Issue by nora-white** [walterra/d3-milestones#16]
Having difficulty getting data to distribute correctly. Even on the observable website, it still doesn't distribute correctly.
Attempted in Chrome and in Firefox. Running on Mac.
Please see attached codesandbox: https://codesandbox.io/s/amazing-surf-1pp2u
Here are screenshots to show what I'm seeing:
![image](https://user-images.githubusercontent.com/15168778/86623630-21615480-bf7f-11ea-8868-63c6119d8228.png)
![image](https://user-images.githubusercontent.com/15168778/86623676-32aa6100-bf7f-11ea-825f-3979e8dbd0cb.png)

Code snippet from codesandbox.io incase the link breaks:
```import React from "react";
import "./styles.css";
import milestones from "d3-milestones/src/main";

export default function App() {
  const renderTimeLine = node => {
    const m = document.getElementById("timeline");
    m.style.height = "500px";
    m.style.width = "700px";
    m.style.margin = "auto";
    m.style.padding = "1px";
    setTimeout(() => {
      const ms = milestones("#timeline")
        .mapping({
          timestamp: "year",
          text: "title"
        })
        .parseTime("%Y")
        .aggregateBy("year")
        .optimize(true)
        .distribution("top-bottom")
        .render([
          { year: 789, title: "Vikings begin attacks on England." },
          { year: 840, title: "Vikings found Dublin in Ireland." },
          { year: 860, title: "Rus Vikings attack Constantinople." },
          {
            year: 866,
            title: "Danish Vikings establish a kingdom in York, England."
          },
          { year: 871, title: "Danish advance is halted in England." },
          { year: 872, title: "Harald I gains control of Norway." }
        ]);
    }, 0);
  };

  return (
    <div className={"container"}>
      <div
        id={"timeline"}
        ref={renderTimeLine}
      />
    </div>
  );
}
```
Any suggestions to help me out? I'm unsure what I'm doing wrong. For my specific scenario as well, we often have around 8 dates to display. With many of the right-most dates looking cramped and unreadable (Exactly like in the screenshots).

**Comment by walterra** [comment]
- I fixed the observable example, unfortunately the CSS file needs to be updated there manually to use the latest CSS from `beta1`.
- When I use the latest CSS the codesandbox example works too.
- Unfortunately having a lot of items on the very right causes issues with the layout algorithm. I don't have a quick fix but will try to think of something.

**Comment by walterra** [comment]
I made some more layout optimizations, it should now be more stable with more labels to the far right.

Before:

![image](https://user-images.githubusercontent.com/230104/103884589-18447200-50df-11eb-96d7-0b1e543aa285.png)

After:

![image](https://user-images.githubusercontent.com/230104/103884650-2abeab80-50df-11eb-8119-d75f210d229d.png)

This will be part of the `1.0.0` release.
