### ISSUE TITLE
using vertical in os_category-lables not working

### ISSUE THREAD

**Issue by HarryF514** [walterra/d3-milestones#23]
`
.orientation('vertical')
`

after adding this   .orientation('vertical') to os_category-labels.html, the webpage just keep loading.

**Comment by walterra** [comment]
Thanks for spotting this. The vertical layout wasn't supported with multiple categories so far. I pushed some fixes (b547700936e8bf35959e34e373a1c447a537ed21, 87ef7f00c085cfb942158b2a6ce348aaad6f9b82) and will make it available as `beta2`. There's still a glitch with the last label at the bottom, will update here once fixed.

![image](https://user-images.githubusercontent.com/230104/103376127-1295cd80-4adc-11eb-9ed8-4950123035f1.png)

**Comment by walterra** [comment]
Fixed the last item glitch in 1dda9874952cb0a9fafe835d24a6c2ee13e69a44

![image](https://user-images.githubusercontent.com/230104/103438961-fa879080-4c38-11eb-9521-e945f93d8d4f.png)
