### ISSUE TITLE
Yarn or NPM

### ISSUE THREAD

**Issue by jcsrb** [walterra/d3-milestones#30]
both `package-lock.json` and `yarn.lock` are present?
which package manager should be used primarily for this project?

side note
the version in `package.json` is `1.0.1` but `package-lock.json` shows `1.0.0`

**Comment by walterra** [comment]
So far I maintained both, so when something in `package.json` changed I ran both `npm install` and `yarn` and committed both lock files. It's no longer considered best practice, so I added this issue to the `2.0.0` milestone to keep only one. Leaning towards `yarn` at the moment.

**Comment by walterra** [comment]
The `main` branch has now been updated to only recommend `yarn`.
