### ISSUE TITLE
Url and open link in new window

### ISSUE THREAD

**Issue by Juuso1** [walterra/d3-milestones#44]
Hi,

I try to use _blank attribute in this module and try to open link in new window.
Where do I add this _blank attribute?

BR,
Juuso

**Comment by Erickud** [comment]
Hello @Juuso1 ,
I have the same issue and I resolve by using in header of html
` <base target="_blank">`
BR

**Comment by walterra** [comment]
[v1.3.0](https://github.com/walterra/d3-milestones/releases/tag/v1.3.0) now includes option `urlTarget` which allows you set the `target` attribute. See [README.md](https://github.com/walterra/d3-milestones#urlTarget) for details.
