### ISSUE TITLE
Is there a way to add text or show text bubble on hover over? 

### ISSUE THREAD

**Issue by oleg-underscore-r** [walterra/d3-milestones#8]
I see there is a mouseOver event handler, but was curious if there was a way to show test bubble on hover. 

Thanks.

**Comment by walterra** [comment]
Hey @OlegForce, sorry for getting back so late, something was wrong with my github notifications. I'm not sure I understand what you mean with `show test bubble on hover`, could you maybe post a mockup of how you imagine this to look like?

**Comment by walterra** [comment]
Closing this since it's been stale for a while now. Please feel free to reopen if you want to follow up.
