### ISSUE TITLE
milestones__group__label-last is not being used 

### ISSUE THREAD

**Issue by jelohipolitocruz** [walterra/d3-milestones#9]
So I'm having this issue that the last element is not having this class, so I tried to update the main.js and added a Math.round in mostRightPosition variable and it worked. do you mind me submitting PR for it?

**Comment by walterra** [comment]
Sounds good, would be great if you'd do a PR!

**Comment by jelohipolitocruz** [comment]
As much as I would like to create a PR for it, git is denying my account

**Comment by jelohipolitocruz** [comment]
![image](https://user-images.githubusercontent.com/18521848/61951395-2b2dba00-afb1-11e9-86ea-d53cf0652b59.png)

I'm having this error

**Comment by walterra** [comment]
I suspect you did not create a fork to your own namespace where you could push? I you have trouble creating the PR, please just post your updated file in a gist or somewhere else and link to it here.

**Comment by jelohipolitocruz** [comment]
Hi @walterra I've created a pull request, I hope you could check that :)

**Comment by jelohipolitocruz** [comment]
Hi walterra, I would just like to follow up on this issue, I submitted a PR :)

**Comment by walterra** [comment]
@jelohipolitocruz Thanks for your contribution, I just merged the PR (#10) and released a new version https://github.com/walterra/d3-milestones/releases/tag/v1.0.0-alpha14
